apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend_db
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: backend_db
  template:
    metadata:
      labels:
        app: backend_db
    spec:
      containers:
        - name: backend
          image: likoste1/board-backend:1.1
          ports:
            - containerPort: 8000
          # 리소스 제한 설정
          resources:
            requests:
              cpu: 1000m # 최소 CPU 1코어
              memory: 512Mi # 최소 메모리 512Mi
            limits:
              cpu: 2000m # 최대 CPU 2코어
              memory: 1024Mi # 최대 메모리 1024Mi

